# Your name and what you do
name: Mayowa Sogbein
bio: Software Engineer

description: Jibola Sogbein's Personal Website

# Profile picture
picture: assets/images/profile.jpeg

# your url: http://USERNAME.github.io
url: https://jibolash.github.io/

# do you need want social media links? true or false
social-media: true
# if you don't have any of social below, comment the line
# facebook: myfacebook
# twitter: jibolash
linkedin: mayowa-sogbein
github: jibolash
email: mayowa.sogbein@gmail.com
# google: mygoogle
# instagram: jibolash
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 3476688/jibola
# quora: Jibola-Sogbein
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# do you need an about section? true or false
about: tfass

# do you need a skills section? true or false
skills: false

# add your skills here
skills-list:
    - Java, Python, JavaScript
    - HTML, CSS, jQuery, Ajax
    - JSP/Servlet, Flask, Express.js
    - Angular, React
    - Spring/JSF, Android
    - MySQL, PostgreSQL, SQLite, MongoDB
    - Eclipse, IntelliJ IDEA, Android Studio, Sublime Text, Git, Docker, Jenkins
    - Agile, Waterfall
    - Tomcat, GlassFish, WildFly

# do you need a projects section? true or false
projects: true

# add your projects here
project-list:
    QuizKnit:
        name: QuizKnit
        description: AI powered web application that generates a quiz based on user provided text. Users can also share the quiz with other people using a custom url.
        url: https://quizknit.com
    Eve:
        name: Eve
        description: Ultra Minimal Single-page Jekyll Template for Building Personal Portfolio Websites. Currently has 50+ Github stars. This website is built with it!
        url: https://github.com/jibolash/Eve
    World-Cup-History:
        name: World Cup  History
        description: npm package for FIFA World cup historical data.
        url: https://github.com/jibolash/world-cup-history

# do you need want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
    - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
